name: Deploy Jupyter Book

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install jupyter-book ghp-import

      - name: Build Jupyter Book
        run: jupyter-book build Covid19_book/

      - name: Deploy to GitHub Pages
        run: |
          ghp-import -n -p -f Covid19_book/_build/html
